HttpSupport : hotfix forNullPointerException
return status 500 instead of server crash

error:
NullPointerException: Cannot load from object array because "args" is null"}