JS. Crypto. Handle error.
In some cases TypeError: crypto.randomUUID is not a function could happen
https://trello.com/c/HrvrOaPd/29468-caa-data-regression